title: 'Light Reader'                      #Name of application, used for page title and home page H1
design: 'mobile'                           #Choose a design, available : html|xml|mobile
nextLink: '&rsaquo;'                       #Next link name (unused for mobile)
prevLink: '&lsaquo;'                       #Previous link name (unused for mobile)
randomLink: 'Random'                       #Random link name (unused for mobile)
proxy:
    url: false                             #Proxy URL, false if not needed
    port: false                            #Proxy port, false if not needed
    user: false                            #Proxy username, false if not needed
    password: false                        #Proxy password, false if not needed
cache:
    maxage: 120                            #Max age and Expires HTTP headers